apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name | default "merchant-config"}}
  namespace: {{ $.Values.namespace | default "default"}}
data:
  {{- (.Files.Glob "configmap/*").AsConfig | nindent 2}}