apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.service.name}}
  namespace: {{ $.Values.namespace  | default "default"}}
  labels:
    {{- include "merchant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.exposePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "merchant.selectorLabels" . | nindent 4 }}
